insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (1, 134, 'Gottlieb-Reichert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (2, 50, 'Dietrich, Krajcik and Konopelski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (3, 142, 'Abernathy-Ratke');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (4, 50, 'Johnson, Orn and Tremblay');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (5, 57, 'Mueller, Mitchell and Bradtke');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (6, 67, 'Braun Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (7, 143, 'Jast and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (8, 53, 'Kassulke-Schimmel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (9, 36, 'Brown LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (10, 68, 'King Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (11, 22, 'Bayer, Shanahan and Beer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (12, 48, 'Hilll-Abbott');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (13, 110, 'Krajcik LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (14, 122, 'Konopelski, Wyman and Herzog');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (15, 97, 'Treutel Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (16, 103, 'Renner-Halvorson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (17, 76, 'Robel, O''Hara and O''Conner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (18, 134, 'Kuvalis, Shields and Hamill');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (19, 82, 'Braun, Conn and Ullrich');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (20, 134, 'Greenfelder-Witting');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (21, 30, 'Stroman and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (22, 130, 'Davis-Nikolaus');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (23, 51, 'Hauck and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (24, 149, 'Jast, Swaniawski and Stehr');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (25, 104, 'Pagac-Welch');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (26, 45, 'Gottlieb, Swift and Vandervort');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (27, 67, 'Morissette, Kulas and Kuphal');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (28, 43, 'Hills, Herman and Schinner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (29, 42, 'Nolan-Schmeler');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (30, 51, 'Murphy, Maggio and Schmidt');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (31, 67, 'Hintz, Hansen and Russel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (32, 138, 'Strosin-Williamson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (33, 56, 'Mueller-Nicolas');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (34, 131, 'Kerluke-Nader');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (35, 81, 'Windler-Miller');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (36, 119, 'Buckridge-Block');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (37, 14, 'Wehner and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (38, 108, 'Harvey LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (39, 136, 'Gleason, Bins and Marks');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (40, 69, 'VonRueden-Mills');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (41, 110, 'Feil-Morar');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (42, 113, 'Krajcik Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (43, 41, 'Weber-Dibbert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (44, 37, 'Zieme, Ratke and Ernser');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (45, 20, 'Fadel, Kreiger and White');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (46, 18, 'Rodriguez, Kautzer and Aufderhar');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (47, 145, 'Hartmann, Bosco and Dibbert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (48, 88, 'Goyette Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (49, 149, 'Jacobs Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (50, 5, 'Welch, Kuphal and Doyle');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (51, 148, 'Hickle, Rohan and Kuhic');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (52, 69, 'Schaefer-Paucek');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (53, 6, 'Mante and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (54, 74, 'Hettinger-Koch');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (55, 94, 'Braun and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (56, 3, 'Pfeffer Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (57, 93, 'Robel LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (58, 112, 'Schoen-Durgan');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (59, 73, 'McCullough Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (60, 36, 'Koelpin, Ondricka and Bechtelar');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (61, 126, 'Tillman-Parker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (62, 74, 'Waelchi Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (63, 65, 'Little, Emmerich and Hahn');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (64, 87, 'Mayert, Braun and Jenkins');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (65, 97, 'Runolfsdottir, West and Medhurst');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (66, 149, 'Dare, Quigley and Treutel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (67, 43, 'Rau Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (68, 64, 'Watsica, Upton and Williamson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (69, 92, 'Paucek-Johnson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (70, 101, 'Jacobi Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (71, 71, 'Schimmel-Buckridge');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (72, 84, 'Moore, Keebler and Harvey');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (73, 132, 'Toy, Powlowski and Murphy');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (74, 145, 'Pagac, Kulas and Kertzmann');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (75, 59, 'Douglas, DuBuque and Ullrich');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (76, 42, 'Purdy, Skiles and Mann');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (77, 25, 'Reichel, Hauck and Padberg');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (78, 8, 'Herzog, Kohler and Boehm');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (79, 18, 'Nader Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (80, 122, 'Moore, Franecki and Walker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (81, 93, 'Boehm-Thompson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (82, 45, 'Schmeler-Grady');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (83, 105, 'Schamberger-Turcotte');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (84, 78, 'White, Beer and McCullough');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (85, 106, 'Collier Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (86, 87, 'Homenick, Metz and Hills');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (87, 85, 'Abshire LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (88, 9, 'Wolff, Bergstrom and Shields');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (89, 1, 'Kiehn, Hilll and Labadie');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (90, 143, 'Ziemann-Kub');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (91, 136, 'Ondricka Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (92, 73, 'McClure LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (93, 148, 'Bartoletti, Murazik and Quitzon');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (94, 82, 'Sanford-Jakubowski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (95, 121, 'Conn Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (96, 77, 'Lemke, Lynch and Rogahn');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (97, 84, 'Parisian, Green and Becker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (98, 43, 'Kuhn-Farrell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (99, 144, 'Becker Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (100, 33, 'Doyle, Green and Schroeder');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (101, 47, 'Denesik Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (102, 21, 'Stanton-Carter');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (103, 122, 'Zemlak-Jaskolski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (104, 134, 'Johnston-Hermann');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (105, 28, 'Will and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (106, 7, 'Raynor, D''Amore and Beer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (107, 113, 'Predovic Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (108, 34, 'Kessler, Muller and Strosin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (109, 111, 'Williamson-Schaefer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (110, 10, 'Waters, O''Hara and Kozey');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (111, 63, 'McClure Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (112, 110, 'Hermann, Tillman and Zieme');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (113, 75, 'Hettinger-Bechtelar');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (114, 81, 'Rutherford-Torphy');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (115, 112, 'Ortiz-Smith');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (116, 27, 'Schneider and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (117, 129, 'Roberts LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (118, 37, 'Von, Koch and O''Connell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (119, 66, 'Bechtelar Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (120, 147, 'Conn-Brakus');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (121, 2, 'Yundt Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (122, 58, 'Schroeder, Conn and Nader');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (123, 55, 'Halvorson LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (124, 53, 'Lemke-Effertz');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (125, 147, 'Hodkiewicz-Lesch');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (126, 49, 'Wintheiser Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (127, 50, 'Heathcote, O''Hara and Pagac');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (128, 142, 'Friesen, Konopelski and Wyman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (129, 7, 'Steuber, MacGyver and Zemlak');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (130, 9, 'Emard LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (131, 57, 'Torphy, King and Ledner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (132, 146, 'MacGyver-Harber');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (133, 10, 'Bins-Wyman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (134, 82, 'Keeling-Botsford');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (135, 74, 'Osinski LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (136, 123, 'Kiehn Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (137, 106, 'Torphy, Feil and Parker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (138, 93, 'Doyle, Strosin and Bergnaum');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (139, 36, 'Huel, Nikolaus and Daniel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (140, 23, 'Rice, Dach and Torp');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (141, 146, 'Grady, Shanahan and Lakin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (142, 145, 'Ankunding, Carroll and Rohan');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (143, 23, 'Lueilwitz, Labadie and Hoppe');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (144, 139, 'Nikolaus-Walker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (145, 131, 'O''Kon-Howell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (146, 26, 'Ernser-Cartwright');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (147, 77, 'Goldner, Bernhard and Howe');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (148, 59, 'Legros-Yost');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (149, 76, 'Jacobi-Rice');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (150, 61, 'Tillman-Hyatt');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (151, 87, 'Reinger Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (152, 134, 'Green and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (153, 49, 'Miller and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (154, 15, 'Hermann Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (155, 128, 'Schuppe-Gottlieb');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (156, 56, 'Koch Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (157, 74, 'King Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (158, 111, 'Marquardt-Rosenbaum');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (159, 126, 'Collins-Gottlieb');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (160, 37, 'Gerlach-Rippin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (161, 137, 'Macejkovic-Glover');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (162, 2, 'Kutch, Heller and Hills');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (163, 95, 'Kris, Lueilwitz and D''Amore');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (164, 23, 'Ward-Maggio');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (165, 58, 'Schneider LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (166, 143, 'Robel, Renner and Thompson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (167, 27, 'Hoppe-Jenkins');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (168, 79, 'Walker-Mann');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (169, 16, 'Terry-Ebert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (170, 116, 'Walker Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (171, 92, 'Farrell Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (172, 29, 'O''Hara, Aufderhar and Mueller');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (173, 96, 'Crist, Ankunding and Wehner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (174, 91, 'Bruen and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (175, 71, 'McDermott Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (176, 64, 'Ryan Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (177, 146, 'Trantow Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (178, 141, 'Bins, Dare and Mitchell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (179, 53, 'Hand Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (180, 99, 'O''Hara, Reinger and Roberts');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (181, 104, 'Langosh, Bode and Reilly');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (182, 94, 'Schimmel, Miller and Medhurst');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (183, 74, 'Littel-Fadel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (184, 81, 'Kessler, Lakin and Hilpert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (185, 95, 'Heller-Ortiz');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (186, 61, 'Jones-Green');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (187, 85, 'Kemmer Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (188, 48, 'Metz LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (189, 75, 'Champlin, VonRueden and Williamson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (190, 116, 'Bergstrom, Grady and Blanda');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (191, 69, 'Borer, Parisian and Jaskolski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (192, 16, 'Gislason and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (193, 48, 'Haley Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (194, 70, 'Stanton, Sauer and Farrell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (195, 24, 'Bruen-Morissette');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (196, 74, 'Monahan, Walker and Rempel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (197, 108, 'Fadel, Walker and Jenkins');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (198, 103, 'Boehm LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (199, 22, 'Wiza LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (200, 1, 'Bradtke and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (201, 64, 'Rice-Ebert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (202, 16, 'Kutch Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (203, 100, 'Boyle-Lebsack');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (204, 121, 'Barton-Miller');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (205, 67, 'Funk, Morar and Bosco');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (206, 16, 'Jenkins Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (207, 31, 'Ankunding and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (208, 77, 'Ward-Lehner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (209, 57, 'Gusikowski, Kohler and Parisian');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (210, 125, 'Little Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (211, 37, 'Runolfsdottir-Mitchell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (212, 124, 'Kris, Upton and Hessel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (213, 107, 'Bayer LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (214, 35, 'Waelchi-Volkman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (215, 53, 'Wehner-Murazik');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (216, 142, 'Marquardt, Medhurst and Thiel');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (217, 70, 'Ortiz and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (218, 28, 'Wolff Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (219, 113, 'Haley-Reinger');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (220, 89, 'Roob Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (221, 14, 'Runte and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (222, 47, 'Larson LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (223, 100, 'Ruecker Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (224, 53, 'Kilback, Balistreri and Bernier');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (225, 36, 'Hilpert, Upton and Klein');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (226, 5, 'Johnson LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (227, 148, 'Dietrich, Schumm and Wilderman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (228, 63, 'Doyle Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (229, 117, 'Schulist, Kerluke and McGlynn');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (230, 145, 'Davis-Bayer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (231, 15, 'Little-Jacobs');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (232, 19, 'Tillman Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (233, 83, 'Kozey Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (234, 96, 'MacGyver-Wolff');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (235, 127, 'Stroman and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (236, 74, 'West Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (237, 25, 'Heller, Schamberger and Glover');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (238, 63, 'Lehner, McDermott and Baumbach');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (239, 150, 'Kris Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (240, 82, 'Wilkinson, Adams and King');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (241, 124, 'Marquardt-Schuppe');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (242, 97, 'Bode-Reichert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (243, 37, 'Carroll and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (244, 44, 'Kerluke-Haag');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (245, 73, 'Green-Hayes');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (246, 86, 'Tremblay and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (247, 41, 'Koelpin Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (248, 94, 'Schmidt-Schamberger');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (249, 12, 'Gaylord-Cruickshank');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (250, 66, 'Moore, Mann and Schuster');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (251, 146, 'Dicki, Berge and Mante');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (252, 121, 'Mohr and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (253, 17, 'Moen-Fay');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (254, 105, 'Heathcote and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (255, 110, 'Ankunding Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (256, 118, 'Kuhic, Schamberger and Terry');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (257, 110, 'Skiles Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (258, 38, 'Mayer LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (259, 28, 'Mosciski, Borer and Koch');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (260, 14, 'Simonis Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (261, 138, 'Crooks Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (262, 94, 'Ferry-O''Kon');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (263, 32, 'Medhurst LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (264, 49, 'Douglas Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (265, 104, 'Muller-Monahan');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (266, 73, 'Block and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (267, 56, 'Ferry Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (268, 28, 'Schamberger, Mann and Cassin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (269, 123, 'O''Connell-Feeney');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (270, 59, 'Davis-Moen');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (271, 82, 'Huels-D''Amore');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (272, 19, 'Fritsch, Stroman and Collins');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (273, 18, 'Gutmann, Hyatt and Spinka');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (274, 126, 'Reichel and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (275, 11, 'Dickens-Jones');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (276, 65, 'Romaguera Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (277, 95, 'Rolfson-Mayer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (278, 144, 'Dooley Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (279, 43, 'Frami-Pfannerstill');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (280, 108, 'Ryan Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (281, 58, 'Durgan, Ankunding and Langworth');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (282, 115, 'Goyette LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (283, 58, 'Kautzer Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (284, 21, 'Daugherty-Schulist');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (285, 102, 'Wilkinson, Lindgren and Turcotte');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (286, 36, 'McCullough-Weissnat');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (287, 81, 'Ritchie, Fritsch and West');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (288, 72, 'Hoppe Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (289, 99, 'Stroman-Barton');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (290, 64, 'Kling Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (291, 18, 'Boyle, Weber and Wisozk');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (292, 48, 'Koepp-Bins');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (293, 70, 'Moen and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (294, 136, 'Koelpin, Walter and Witting');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (295, 142, 'Ruecker Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (296, 6, 'Beatty, Skiles and Christiansen');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (297, 12, 'Bogan Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (298, 63, 'Leannon, Gorczany and Funk');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (299, 136, 'Murray, Adams and Powlowski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (300, 123, 'Spencer-O''Conner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (301, 84, 'Friesen-Pfannerstill');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (302, 46, 'Heller, Quigley and Effertz');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (303, 26, 'Hodkiewicz, Dickinson and Stehr');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (304, 106, 'Yundt and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (305, 66, 'Nienow, Johnson and Walter');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (306, 124, 'Bailey-Kuhlman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (307, 118, 'Walter-Waelchi');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (308, 14, 'Schumm-Rolfson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (309, 25, 'Veum-Durgan');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (310, 127, 'Pollich, Hammes and Weber');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (311, 51, 'Haag and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (312, 64, 'Schmitt-Yundt');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (313, 123, 'Goyette and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (314, 77, 'Gibson LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (315, 67, 'Runte, Erdman and Kuhn');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (316, 49, 'Sanford LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (317, 67, 'Pouros-West');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (318, 59, 'Feest Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (319, 146, 'Rippin and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (320, 102, 'Champlin, Wunsch and Hansen');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (321, 80, 'Bernhard, Cummerata and Lindgren');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (322, 129, 'Barton, Rowe and Cassin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (323, 124, 'Emmerich LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (324, 11, 'Bernhard and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (325, 97, 'Osinski-Gaylord');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (326, 122, 'Rohan LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (327, 61, 'Hermann-Waelchi');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (328, 24, 'Kessler-Legros');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (329, 47, 'Rau Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (330, 137, 'Volkman-Heathcote');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (331, 15, 'Beahan LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (332, 77, 'Ebert-Aufderhar');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (333, 20, 'Kulas, Waelchi and Morissette');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (334, 129, 'Koss-Haag');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (335, 23, 'Olson, Sanford and Erdman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (336, 36, 'Kunde-VonRueden');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (337, 90, 'D''Amore, Runte and O''Conner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (338, 124, 'Reinger and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (339, 27, 'Stanton-Mayer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (340, 128, 'Schultz Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (341, 43, 'Wunsch-Rippin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (342, 25, 'Wyman-Barton');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (343, 14, 'Konopelski, Mraz and Kilback');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (344, 3, 'Bruen LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (345, 67, 'Hand LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (346, 5, 'Gusikowski and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (347, 114, 'Hamill, Sanford and Windler');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (348, 18, 'Powlowski Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (349, 90, 'Veum Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (350, 99, 'Hauck and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (351, 17, 'Brown Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (352, 21, 'Kris, Cole and Sawayn');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (353, 148, 'Kertzmann-Jacobi');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (354, 100, 'Fisher-Mills');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (355, 20, 'Ondricka-Johnson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (356, 55, 'Schinner, Schulist and Hintz');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (357, 35, 'Ferry, Vandervort and Stanton');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (358, 81, 'Goldner and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (359, 120, 'Mante and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (360, 63, 'Heller-Howe');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (361, 10, 'Pfannerstill Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (362, 30, 'Hartmann-Wolf');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (363, 46, 'Padberg-Herman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (364, 9, 'Gleichner-Gorczany');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (365, 123, 'Gerlach, Bayer and Gorczany');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (366, 146, 'Runte-Olson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (367, 87, 'Legros Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (368, 65, 'Bartell and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (369, 12, 'Nolan-Balistreri');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (370, 9, 'Grant-Rodriguez');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (371, 36, 'Parker, Moore and Hagenes');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (372, 127, 'Reichert-Romaguera');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (373, 107, 'Koepp, Boyle and Hegmann');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (374, 110, 'Adams, Adams and Mayert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (375, 113, 'Feeney LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (376, 118, 'Kihn Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (377, 120, 'Herman LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (378, 124, 'Ernser, Quitzon and Ondricka');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (379, 144, 'Rutherford, Moore and Ritchie');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (380, 92, 'Nicolas Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (381, 12, 'Feest, Homenick and Rolfson');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (382, 73, 'Feest, Koepp and Pollich');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (383, 131, 'Grady LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (384, 134, 'Reinger Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (385, 48, 'Schiller, Hermann and O''Connell');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (386, 77, 'Wunsch Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (387, 59, 'Haley-Kerluke');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (388, 90, 'Kuvalis Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (389, 130, 'Mertz Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (390, 105, 'Morar, Zemlak and Tromp');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (391, 116, 'Mann Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (392, 111, 'Medhurst and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (393, 107, 'Dooley-Murazik');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (394, 145, 'Cassin, Koch and Schmeler');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (395, 69, 'Metz-Conn');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (396, 98, 'Boyer, Barton and Kulas');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (397, 79, 'Braun, Nikolaus and Flatley');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (398, 130, 'Aufderhar, Bode and Reynolds');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (399, 124, 'Ebert Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (400, 110, 'Borer Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (401, 22, 'Kertzmann-Hermann');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (402, 80, 'Grant, Lueilwitz and Lowe');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (403, 135, 'Trantow LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (404, 58, 'Hoeger and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (405, 140, 'Dibbert-Goldner');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (406, 25, 'Kovacek-Hyatt');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (407, 30, 'Beatty-Langworth');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (408, 124, 'Leannon and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (409, 74, 'Lubowitz, Koepp and Windler');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (410, 11, 'Cartwright and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (411, 25, 'Murphy, Zemlak and Crooks');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (412, 99, 'Brown LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (413, 18, 'Grady-Hilll');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (414, 105, 'Price LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (415, 134, 'Roob and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (416, 46, 'MacGyver-Wilderman');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (417, 121, 'Turner-Becker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (418, 133, 'Reilly, Emard and O''Reilly');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (419, 110, 'Hackett, Crooks and Shields');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (420, 92, 'Halvorson-Rippin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (421, 150, 'Robel Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (422, 49, 'Nikolaus Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (423, 4, 'Bergstrom-Hoeger');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (424, 108, 'Miller-Kshlerin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (425, 140, 'Oberbrunner, Trantow and Marvin');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (426, 30, 'Buckridge-Kutch');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (427, 47, 'Schoen-Kemmer');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (428, 53, 'Ruecker Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (429, 112, 'Hilpert, Reilly and Ebert');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (430, 4, 'Ullrich Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (431, 75, 'Beahan Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (432, 73, 'Koch-Ruecker');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (433, 79, 'Farrell LLC');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (434, 147, 'Smitham and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (435, 52, 'Lakin, Anderson and Hills');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (436, 126, 'Bechtelar, Abernathy and Dietrich');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (437, 53, 'Kemmer-Connelly');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (438, 52, 'Anderson, Schimmel and Barrows');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (439, 122, 'Toy Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (440, 106, 'Schroeder and Sons');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (441, 91, 'Davis Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (442, 93, 'Koss, Abshire and Nolan');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (443, 44, 'Daugherty, Heidenreich and D''Amore');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (444, 123, 'Barton, Romaguera and Heidenreich');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (445, 73, 'Orn Inc');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (446, 54, 'Sauer-Hand');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (447, 68, 'Zboncak-Osinski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (448, 79, 'Pagac Group');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (449, 23, 'Gutkowski, Sawayn and Osinski');
insert into rodzaj (id, rodzina_id, nazwa_rodzaju) values (450, 22, 'Fadel, Aufderhar and Kihn');
