insert into rodzina (id, rzad_id, nazwa_rodziny) values (1, 8, 'Mosciski-Bartoletti');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (2, 17, 'Fahey-Gorczany');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (3, 15, 'Kling-Mitchell');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (4, 15, 'Hayes, Jacobi and Hickle');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (5, 1, 'Rutherford, Terry and Kessler');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (6, 14, 'Considine, Boehm and Hintz');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (7, 8, 'Leuschke-Weber');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (8, 13, 'Konopelski, White and Denesik');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (9, 13, 'Marvin Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (10, 4, 'Kuphal Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (11, 6, 'Weissnat-Walker');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (12, 2, 'Kiehn-Stehr');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (13, 14, 'Langosh-Stamm');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (14, 22, 'Schroeder-Champlin');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (15, 10, 'Rempel Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (16, 8, 'MacGyver, Grant and Witting');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (17, 14, 'Sawayn LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (18, 21, 'Osinski, Gottlieb and Hahn');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (19, 9, 'Mosciski, Gusikowski and Bergstrom');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (20, 16, 'Rowe-Mitchell');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (21, 20, 'Wintheiser-Orn');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (22, 11, 'Fadel-Huel');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (23, 16, 'Ortiz Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (24, 2, 'Konopelski, Walsh and Powlowski');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (25, 14, 'Green-Huel');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (26, 13, 'Spinka LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (27, 15, 'Champlin, Jacobi and Anderson');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (28, 25, 'Wuckert-Schneider');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (29, 24, 'Bergstrom Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (30, 12, 'Cummerata Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (31, 22, 'Keeling Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (32, 9, 'Kovacek-Ebert');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (33, 6, 'Gottlieb Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (34, 8, 'Schulist Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (35, 13, 'Rolfson LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (36, 13, 'Bailey, Gislason and Beatty');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (37, 24, 'Waelchi, Oberbrunner and Breitenberg');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (38, 21, 'Rolfson, Nikolaus and Kozey');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (39, 22, 'Tillman-Bahringer');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (40, 31, 'Reinger-Ruecker');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (41, 20, 'Bergnaum and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (42, 12, 'Monahan-Murazik');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (43, 29, 'Gutkowski, Schaefer and Goyette');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (44, 19, 'Robel-Kuhlman');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (45, 17, 'Roob Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (46, 18, 'Sipes-Cartwright');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (47, 28, 'Zulauf Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (48, 2, 'Wuckert Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (49, 7, 'Carter, Mann and Nolan');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (50, 21, 'Hilll LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (51, 29, 'Turcotte LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (52, 25, 'Cole-Schiller');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (53, 12, 'Crooks and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (54, 1, 'Ruecker-Goldner');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (55, 23, 'Wyman Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (56, 8, 'Weissnat-Casper');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (57, 31, 'Strosin Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (58, 29, 'Barrows, Dach and Torphy');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (59, 32, 'Shields Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (60, 32, 'Lindgren-Kuhn');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (61, 29, 'Toy-Goyette');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (62, 31, 'Leuschke Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (63, 21, 'Collins and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (64, 16, 'Lehner-Goyette');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (65, 22, 'Huel-Cummings');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (66, 5, 'Lemke LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (67, 9, 'Sauer Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (68, 21, 'Wiza LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (69, 19, 'Hammes-Steuber');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (70, 8, 'Lueilwitz, Herman and Wisoky');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (71, 28, 'Schimmel, DuBuque and Kemmer');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (72, 1, 'Okuneva and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (73, 30, 'King, Price and Hansen');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (74, 25, 'Auer Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (75, 12, 'Abernathy, Rohan and Oberbrunner');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (76, 32, 'Lynch and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (77, 2, 'Schiller-Glover');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (78, 28, 'Blick and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (79, 22, 'Wilderman, Prosacco and Roberts');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (80, 12, 'Beier-Heathcote');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (81, 30, 'Koepp Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (82, 10, 'Klocko, Shanahan and Kemmer');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (83, 30, 'Pollich, Stamm and Koch');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (84, 16, 'Huels-Jaskolski');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (85, 21, 'Considine, Leuschke and Kertzmann');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (86, 7, 'Medhurst-Nitzsche');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (87, 13, 'Kunde LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (88, 16, 'Pacocha-Rodriguez');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (89, 30, 'Hermann Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (90, 9, 'Corwin-Donnelly');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (91, 1, 'Effertz, Stark and Botsford');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (92, 21, 'Stark-Bruen');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (93, 23, 'Ziemann LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (94, 14, 'Blanda and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (95, 5, 'Jenkins, Kiehn and Satterfield');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (96, 8, 'Leuschke Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (97, 15, 'Bogisich-Bahringer');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (98, 19, 'Price, Wilderman and Hirthe');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (99, 9, 'Huel Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (100, 26, 'Schuster LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (101, 15, 'Simonis, Mitchell and Schmidt');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (102, 16, 'Gusikowski, Hills and Ullrich');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (103, 29, 'Rutherford Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (104, 12, 'Corkery-Ratke');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (105, 3, 'Hayes Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (106, 25, 'Ortiz LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (107, 31, 'Orn-Gutmann');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (108, 31, 'Davis, Moore and Cummings');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (109, 22, 'Olson Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (110, 26, 'Blanda, Hickle and Zemlak');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (111, 30, 'Cole, Durgan and Grady');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (112, 7, 'Schaefer, Shields and Predovic');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (113, 22, 'Hammes, Murphy and Bernier');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (114, 2, 'Adams, Trantow and Moen');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (115, 1, 'Douglas LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (116, 15, 'Bode, Carroll and Herman');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (117, 27, 'Turner-Sipes');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (118, 1, 'Bogisich-Funk');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (119, 14, 'Veum-Beatty');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (120, 28, 'Haag-Gusikowski');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (121, 32, 'Grimes-Daniel');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (122, 30, 'Wolf, Trantow and Durgan');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (123, 12, 'Wyman and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (124, 31, 'Gibson, Crona and Altenwerth');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (125, 20, 'Thiel-VonRueden');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (126, 4, 'Schroeder, Goldner and DuBuque');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (127, 28, 'Dach, Muller and Koss');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (128, 30, 'D''Amore, Thiel and Murphy');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (129, 5, 'Frami-Stroman');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (130, 5, 'Crooks-Rowe');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (131, 15, 'Ryan-Hayes');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (132, 7, 'Hamill, Mills and Purdy');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (133, 4, 'Dooley, Dietrich and Goyette');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (134, 27, 'Bauch-Lynch');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (135, 3, 'Lakin-Bauch');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (136, 32, 'Stroman and Sons');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (137, 26, 'Von, Ebert and Hoeger');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (138, 12, 'Satterfield-Hilpert');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (139, 25, 'Bernhard-Lockman');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (140, 7, 'Towne-Kris');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (141, 31, 'Adams Group');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (142, 4, 'Schiller Inc');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (143, 23, 'Towne-Trantow');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (144, 7, 'Stoltenberg-Muller');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (145, 15, 'Batz, Schaefer and Stamm');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (146, 18, 'Hudson, Bauch and Bashirian');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (147, 6, 'Leffler-Kunze');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (148, 1, 'Bashirian, Schinner and Buckridge');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (149, 32, 'Gislason LLC');
insert into rodzina (id, rzad_id, nazwa_rodziny) values (150, 16, 'Heller, Lesch and Fritsch');
